const fs=require('fs'),vm=require('vm');
globalThis.document={getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]};
globalThis.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
console.warn=()=>{};
vm.runInThisContext(fs.readFileSync(__dirname+'/js/engine.js','utf8'),{filename:'engine.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/app.js','utf8'),{filename:'app.js'});
const B=globalThis.BBGM,A=globalThis.BBGM_APP_TEST,w=B.createWorld(),team=w.clubs[0],cap=team.roster[0],p=team.roster[1],p2=team.roster[2];
const st={season:'2026/27',currentDate:'2026-11-02',userClubId:team.id,world:w,calendar:[],standings:{},inbox:[],manager:{reputation:52,staffManagement:50},coachManagement:{relationship:72},lockerRoom:{captainId:cap.id,relationshipOverrides:{},decisionHistory:[]}};
A.setState(st);
const dispute={id:501,type:'DECISION',title:'Disputa',text:'Tensión',playerId:p.id,otherPlayerId:p2.id,resolved:false,choices:[{label:'Delegar',effect:'LOCKER_CAPTAIN'}]};
st.inbox.push(dispute);
const factors=A.captainInterventionChance(dispute);
if(!factors.available||factors.chance<.18||factors.chance>.88)throw new Error(`Probabilidad inválida: ${factors.chance}`);
const before=A.chemistryPair(p,p2),result=A.resolveDecision(501,0,true),after=A.chemistryPair(p,p2);
if(!dispute.resolved||!dispute.captainResolution||!['SUCCESS','PARTIAL','FAILURE'].includes(dispute.captainResolution.outcome))throw new Error('No se guardó el desenlace del capitán');
if(!result||before===after||st.lockerRoom.decisionHistory.length!==1)throw new Error('La delegación no produjo consecuencias persistentes');
const playerEvent={id:502,type:'DECISION',title:'Minutos',text:'Pide más minutos',playerId:p.id,resolved:false,choices:[{label:'Delegar',effect:'PLAYER_CAPTAIN'}]};
st.inbox.push(playerEvent);A.resolveDecision(502,0,true);
if(!playerEvent.resolved||!playerEvent.decisionResult||st.lockerRoom.decisionHistory.length!==2)throw new Error('La petición de minutos no se resuelve mediante el capitán');
console.log(JSON.stringify({chance:Math.round(factors.chance*100),disputeOutcome:dispute.captainResolution.outcome,relationship:[before,after],playerOutcome:playerEvent.captainResolution.outcome,history:st.lockerRoom.decisionHistory.length,ok:true},null,2));
