const fs=require('fs'),vm=require('vm');
globalThis.document={getElementById:()=>null};
globalThis.localStorage={getItem:()=>null,setItem:()=>{}};
vm.runInThisContext(fs.readFileSync(__dirname+'/js/engine.js','utf8'),{filename:'engine.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/app.js','utf8'),{filename:'app.js'});
const B=globalThis.BBGM,A=globalThis.BBGM_APP_TEST,w=B.createWorld();
const standings={};
for(const co of w.competitions.filter(c=>c.standings)) standings[co.id]=Object.fromEntries(co.clubIds.map(id=>[id,{clubId:id,gp:0,w:0,l:0,pf:0,pa:0}]));
const st={version:'0.15.0',season:'2026/27',currentDate:'2026-09-01',userClubId:1,world:w,history:[],calendar:[],standings,board:{confidence:70,objectives:[]},sponsorship:{active:null,offers:[],brandReputation:60},academy:{players:[]},scouting:{staff:w.scoutStaff||[],assignments:[],knowledge:{}},manager:{scouting:50}};
A.setState(st);A.ensureV15State();
const bask=w.clubs.find(c=>c.id===1),rival=w.clubs.find(c=>c.id===2);
if(!w.clubs.every(c=>Number.isFinite(c.financialHealth)&&Number.isFinite(c.commercialPower)))throw new Error('Clubes sin perfil financiero');
const start=bask.cashBudget;A.financeEntry(bask,'INCOME','TEST',1000000,'Test ingreso');
if(bask.cashBudget!==start+1000000)throw new Error('financeEntry no modifica caja correctamente');
const beforeEntries=st.economy.entries.length;
A.processMatchEconomy({id:'T1',competitionId:'ACB',homeClubId:bask.id,awayClubId:rival.id,date:'2026-09-20'});
if(st.economy.entries.length<=beforeEntries)throw new Error('Partido no genera apuntes económicos');
const once=bask.cashBudget;A.processMatchEconomy({id:'T1',competitionId:'ACB',homeClubId:bask.id,awayClubId:rival.id,date:'2026-09-20'});
if(bask.cashBudget!==once)throw new Error('Partido económico se procesa dos veces');
const t=A.financeTotals();if(!(t.income>0&&t.expense>0))throw new Error('Totales económicos incompletos');
const offers=A.createSponsorOffers('2026/27');if(offers.length!==4)throw new Error('Se esperaban cuatro patrocinadores');
if(!offers.some(o=>o.bonuses.some(b=>b.code==='FIN_HEALTH')))throw new Error('Sin patrocinador financiero/cantera');
const fb=A.financialBoardState();if(typeof fb.ok!=='boolean')throw new Error('Objetivo financiero no evaluable');
console.log(JSON.stringify({clubs:w.clubs.length,health:Math.round(bask.financialHealth),entries:st.economy.entries.length,income:t.income,expense:t.expense,balance:t.balance,sponsors:offers.length,financialObjective:fb.ok,ok:true},null,2));
