const fs=require('fs'),vm=require('vm');
globalThis.document={getElementById:()=>null};
globalThis.localStorage={getItem:()=>null,setItem:()=>{}};
vm.runInThisContext(fs.readFileSync(__dirname+'/js/engine.js','utf8'),{filename:'engine.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/js/app.js','utf8'),{filename:'app.js'});
const B=globalThis.BBGM,A=globalThis.BBGM_APP_TEST,w=B.createWorld();
const standings={};for(const co of w.competitions.filter(c=>c.standings))standings[co.id]=Object.fromEntries(co.clubIds.map(id=>[id,{clubId:id,gp:0,w:0,l:0,pf:0,pa:0}]));
const bask=w.clubs.find(c=>c.id===1),opp=w.clubs.find(c=>c.id===2),res=B.simulateMatch(bask,opp,16016);
const match={id:'V16-1',competitionId:'ACB',homeClubId:bask.id,awayClubId:opp.id,date:'2026-10-01',status:'PLAYED',homeScore:res.homeScore,awayScore:res.awayScore,result:res};
const s=standings.ACB;bask.id&&(()=>{const h=s[bask.id],a=s[opp.id];h.gp++;a.gp++;h.pf+=res.homeScore;h.pa+=res.awayScore;a.pf+=res.awayScore;a.pa+=res.homeScore;if(res.homeScore>res.awayScore){h.w++;a.l++}else{a.w++;h.l++}})();
const st={version:'0.16.0',season:'2026/27',currentDate:'2027-06-25',userClubId:1,world:w,history:[{matchId:match.id,date:match.date}],calendar:[match],standings,special:{champions:{},series:{}},board:{confidence:72,objectives:[]},manager:{reputation:52},sponsorship:{active:null,offers:[],brandReputation:60},academy:{players:[]},scouting:{staff:w.scoutStaff||[],assignments:[],knowledge:{}},medical:{doctor:{}},nba:{draftHistory:[],rights:{}},nationalTeams:{callups:[],history:[]}};
A.setState(st);A.ensureV15State();A.ensureV16State();
const row={games:10,minutes:300,points:180,assists:45,turnovers:20,value:190,twoMade:35,twoAttempted:70,threeMade:25,threeAttempted:65,ftMade:35,ftAttempted:40};
const adv=A.advancedStatsRow(row);if(!(adv.tsPct>0&&adv.efgPct>0&&adv.pts36>0&&adv.astTo>0))throw new Error('Advanced stats invalid');
A.archiveCurrentSeason();if(st.seasonArchive.length!==1)throw new Error('Season archive missing');A.archiveCurrentSeason();if(st.seasonArchive.length!==1)throw new Error('Season archive duplicated');
A.evaluateAchievements(false);const rec=A.currentUserGameRecords();if(!rec.highestTeamScore||!rec.playerPts)throw new Error('Current records missing');
const cr=A.careerRecordSummary();if(cr.seasons!==1)throw new Error('Career season count invalid');
console.log(JSON.stringify({clubs:w.clubs.length,archive:st.seasonArchive.length,ts:+adv.tsPct.toFixed(1),efg:+adv.efgPct.toFixed(1),pts36:+adv.pts36.toFixed(1),records:{score:rec.highestTeamScore.value,playerPts:rec.playerPts.value},achievements:Object.keys(st.achievements.unlocked).length,ok:true},null,2));
