const fs=require('fs'),vm=require('vm');
globalThis.document={getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]};
globalThis.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
console.warn=()=>{};
vm.runInThisContext(fs.readFileSync('js/engine.js','utf8'),{filename:'engine.js'});
vm.runInThisContext(fs.readFileSync('js/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync('js/app.js','utf8'),{filename:'app.js'});
const A=globalThis.BBGM_APP_TEST,world=globalThis.BBGM.createWorld();
const state={season:'2026/27',currentDate:'2026-09-19',userClubId:1,world,calendar:[],standings:{},inbox:[],history:[],manager:{reputation:50},board:{confidence:72}};
A.setState(state);
const match={id:'FINAL-SEQUENCE',date:'2026-09-19',homeClubId:1,awayClubId:2};
const live=A.matchDecisionLiveScoreV48(match,'LAST_SHOT');
if(Math.abs(live.home-live.away)>2)throw new Error('El marcador previo de última posesión no es coherente');
state.matchDecisionV48={pending:{matchId:match.id,type:'LAST_SHOT',choice:'THREE',choiceLabel:'Buscar el triple',title:'Última posesión',clock:'0:08',live},history:[{matchId:match.id,type:'LAST_SHOT',choice:'THREE',live}]};
const result={homeScore:104,awayScore:83};
A.applyMatchDecisionV48(match,result);
const maxExpected=Math.max(live.home,live.away)+3;
if(result.homeScore>maxExpected||result.awayScore>maxExpected)throw new Error('El resultado final no parte del marcador mostrado al usuario');
if(!result.matchDecision?.summary)throw new Error('Falta la narración de la jugada decisiva');
console.log(JSON.stringify({live,final:{home:result.homeScore,away:result.awayScore},sameSequence:true,ok:true},null,2));
